### ISSUE TITLE
magrittr like syntax

### ISSUE THREAD

**Issue by bramtayl** [one-more-minute/Lazy.jl#15]
R's magrittr has a neat feature pertaining to chaining. Piping can be done to a consistent ordered argument (first), or to an argument specified by syntax (_) (well, . , but I will replace it with _ here).

If a chain entry contains a _ by itself as an argument, the second behavior is used. This is also the case if a chain entry is wrapped in curly brackets { } . Otherwise, the first behavior is used.

This syntax would remove the need for a `@>` `@as` distinction, and as a side benefit, could cut down on the number of _'s in my code.

**Comment by one-more-minute** [comment]
So something like:
```julia
@> [1,2,3] map(square) reduce(+) (_ + _)
```
?

**Comment by bramtayl** [comment]
I'm not sure (reduce always confuses me).

Here's an example

```julia
function sum_test(a) = a
function sum_test(a, b) = a + b

@> 1 sum_test( _ + 1) = 1 + (1 + 1)
@> 1 { sum_test( _ + 1) } = 1 + 1
@> 1 sum_test( _ ) = 1
```

**Comment by bramtayl** [comment]
Another useful feature from magrittr is %<>% (maybe @<> in Julia?)

```
a = 1
@<> a sum_test(1)
# a = a + 1
```

**Comment by bramtayl** [comment]
As a side note, I'm finding it irksome that my code for `@as_first` and `@as_last` is identical except for one line. Is there a more elegant way to do it in Julia that avoids duplicated code?
