### ISSUE TITLE
Conflicting function names in Julia 0.4

### ISSUE THREAD

**Issue by boathit** [one-more-minute/Lazy.jl#27]
The Julia 0.4 version has added the functions `take, drop, cycle, range,  rest` which conflict with the counterparts in Lazy.jl now, and `using Lazy` would trigger the warnings:
```
WARNING: using Lazy.take in module Main conflicts with an existing identifier.
WARNING: using Lazy.range in module Main conflicts with an existing identifier.
WARNING: using Lazy.rest in module Main conflicts with an existing identifier.
WARNING: using Lazy.cycle in module Main conflicts with an existing identifier.
WARNING: using Lazy.drop in module Main conflicts with an existing identifier.
``` 
thus it's necessary to import those functions from Base in order to be compatible with version 0.4+

**Comment by one-more-minute** [comment]
A PR for this would be very welcome if you're up for it ;)

**Comment by boathit** [comment]
`take, drop, rest` can be fixed easily via dispatch, but the methods of `range, cycle` defined in Lazy.jl actually are conflicted with the ones in Base, do you think it's a good idea to rename them?

**Comment by one-more-minute** [comment]
Let's just not export them, then people can call Lazy.cycle etc. if they need it.

**Comment by boathit** [comment]
Got it.
