### ISSUE TITLE
Error with seq(itr)

### ISSUE THREAD

**Issue by boathit** [one-more-minute/Lazy.jl#30]
`seq(itr)` will throw an error when applying to an iterator, such as 
```
Lazy.seq(1:5)

Error showing value of type Lazy.LazyList:
ERROR: UndefVarError: x not defined
 [inlined code] from /Users/fineday/.julia/v0.4/Lazy/src/macros.jl:214
 in anonymous at /Users/fineday/.julia/v0.4/Lazy/src/Lazy.jl:82
 in isempty at /Users/fineday/.julia/v0.4/Lazy/src/Lazy.jl:78
 in writemime at /Users/fineday/.julia/v0.4/Lazy/src/Lazy.jl:128
 in display at REPL.jl:115
 in display at REPL.jl:118
 [inlined code] from multimedia.jl:151
...
```

I traced the error to the function `seq(itr, state)` and it seems the error originates from the definition of macro `@with`, because when rewriting the `seq(itr, state)` like 
```
seq(itr, state) = 
    @lazy done(itr, state) ? [] :
        begin x, state = next(itr, state)
            prepend(x, seq(itr, state))
        end
```
the error disappears both `seq(1:5)` and `seq(take([1,2,3,4,5], 3)` works well

**Comment by boathit** [comment]
If you guys agree with me, I will make a PR

**Comment by one-more-minute** [comment]
Sure, a PR would be great!

**Comment by boathit** [comment]
Hi Mike, A PR has been submitted, but it needs to point out that currently `let x, y = next(1:5, start(1:5)) end` cannot be deconstructed correctly in Julia, the value of `y` will be a tuple `(1,2)` and `x` will not be defined. That's the reason why `seq(itr)` fails to work previously as the `let` expression is used in macro `@with`.

**Comment by boathit** [comment]
PR merged.
